uiowaSEP2024/004_SleepTrak

- .github/workflows/web-ci.yml
Created first CI workflow that builds and tests Node.js code.
https://septeam4.atlassian.net/browse/T4-19
> initial web-ci.yml setup

- package-lock.json
- web/jest.config.cjs
- web/package.json
- web/src/__tests__/App.test.tsx
- web/src/__tests__/components/Header.test.tsx
- web/src/__tests__/components/Root.test.tsx
- web/src/__tests__/components/Sidebar.test.tsx
- web/src/components/Header.tsx
- web/src/components/Root.tsx
- web/src/components/Sidebar.tsx
- web/src/main.tsx
- web/src/util/ColorSchemeToggle.tsx
- web/src/util/setupDomTests.ts
- web/tsconfig.json
- Configured Jest to work with Typescript for the web app
- Added tests for already existing components - Root, Sidebar, Header
https://septeam4.atlassian.net/browse/T4-63?atlOrigin=eyJpIjoiYWI4OTg3MDI0MjY1NDk5YmEzZGJjMzNlOTkzNmZmNDAiLCJwIjoiaiJ9
> Existing components test

- mobile/App.tsx
- mobile/README.md
- mobile/__tests__/App.test.tsx
- mobile/__tests__/pages/HomeScreen.test.tsx
- mobile/__tests__/pages/SettingScreen.test.tsx
- mobile/babel.config.js
- mobile/package.json
- mobile/src/navigation/MainNavigator.tsx
- mobile/src/pages/HomeScreen.tsx
- mobile/src/pages/SettingScreen.tsx
- yarn.lock
- Added the main navigation tab for the app 
- Installed UI library [React Native Paper](https://reactnativepaper.com/)
- Jest configuration
> <Mobile> Adding UI library and Test Configuration

- backend/src/app.js
Takes away the origin URLs for CORS. CORS is the protocol that allows browsers to connect with secure APIs. The URLs are not needed and they were causing the CORS to malfunction. Taking them away fixes the issue.
N/A
> [fix] fixes issue with CORS when given callback url.

- common_styles/colors.js
Made a common color palette for the mobile/web. The colors are taken from Camila's Brandbook.
> [style] Color palette

- .github/workflows/test.yml
- mobile/package.json
- mobile/report.json
- package.json
- web/jest.config.cjs
- web/package.json
- web/report.json
Added code coverage report to github action workflow
https://septeam4.atlassian.net/browse/T4-67
> [Github Action] Code coverage report 

- backend/Dockerfile
- backend/db/Dockerfile
- backend/package.json
- backend/wait-for-it.sh
- docker-compose.yml
Creates a docker container for our postgres database.  Docker database is automatically migrated and seeded whenever you run the container.  To make this work, include OVERRIDE_DATABASE_URL, DB_NAME, DB_USER, DB_PASSWORD in your project-level .env file (it needs to be there for the docker-compose to read the env var).
Run $ docker compose up --build.  This will start the web, backend, and postres containers and the web & backend will hot-reload if you make source code changes (no need to restart containers all the time).
https://septeam4.atlassian.net/browse/T4-72
> Docker Database Container

- .github/workflows/coverage.yml
- .github/workflows/test.yml
- backend/package.json
- backend/report.json
I separated the coverage report and testing, so the testing should work, as long as the tests are passing.
For the coverage, it creates a label on the PR (as you can see below), but the workflow still fails because of workflow permission (i think).
> [Github Action] Coverage

- backend/prisma/migrations/20240313015735_updates_events_to_handle_food/migration.sql
- backend/prisma/schema.prisma
- backend/src/controllers/events.ts
- mobile/__tests__/screens/FoodTrackingScreen.test.tsx
- mobile/ios/Podfile.lock
- mobile/ios/mobile.xcodeproj/project.pbxproj
- mobile/package.json
- mobile/src/components/inputs/NotesTextInput.tsx
- mobile/src/navigations/HomeStack.tsx
- mobile/src/screens/FoodTrackingScreen.tsx
- mobile/src/screens/HomeScreen.tsx
- mobile/src/utils/db.tsx
Creates the food tracking screen and links it to the database. Updates events table to handle extra fields from feeding events. Also, fixes minor bugs in backend controllers.
https://septeam4.atlassian.net/browse/T4-9?atlOrigin=eyJpIjoiOGIxMTE0NDE2N2JlNGJiYzlkMWUwZWM3ZjlmYjY2ZTUiLCJwIjoiaiJ9
https://github.com/uiowaSEP2024/004_SleepTrak/assets/42824421/f36fe0fa-146b-498b-893b-05cf9430b238
> [feat] Food tracking

- mobile/__tests__/screens/EventsScreen.test.tsx
- mobile/ios/Podfile.lock
- mobile/ios/mobile.xcodeproj/project.pbxproj
- mobile/src/navigations/HomeStack.tsx
- mobile/src/screens/EventScreen.tsx
- mobile/src/screens/EventsScreen.tsx
- mobile/src/screens/HomeScreen.tsx
Adds an event page with rudimentary event cards and date selection. Also, adds testing and fixes some bugs in the home screen. 
https://github.com/uiowaSEP2024/004_SleepTrak/assets/42824421/53918b7a-1546-4c92-85a4-1b05301a2957
https://septeam4.atlassian.net/browse/T4-84?atlOrigin=eyJpIjoiOTJiNTE2MGE5MzkzNDYwNmJhODI5OTdiMzhhZmM3OWUiLCJwIjoiaiJ9
> [feat] Events page

- backend/prisma/migrations/20240319212025_add_sleep_window_table/migration.sql
- backend/prisma/migrations/20240322223258_adds_crib_time_to_event/migration.sql
- backend/prisma/migrations/20240323040736_rename_id_to_window_id/migration.sql
- backend/prisma/migrations/20240323041254_rename_notes_to_note/migration.sql
- backend/prisma/schema.prisma
- backend/src/app.ts
- backend/src/controllers/sleep-windows.ts
- backend/src/routes/sleep-windows.ts
- backend/src/services/sleep-windows.ts
- backend/test/api/sleep-windows.test.ts
- backend/test/prismaSpy.ts
- mobile/.eslintrc.yml
- mobile/__tests__/components/buttons/cribButton.test.tsx
- mobile/__tests__/components/inputs/EditTimePicker.test.tsx
- mobile/__tests__/screens/EditWindowScreen.test.tsx
- mobile/__tests__/screens/SleepTimerScreen.test.tsx
- mobile/src/components/buttons/CribButton.tsx
- mobile/src/components/inputs/EditTimePicker.tsx
- mobile/src/components/views/ElapsedTimeDisplay.tsx
- mobile/src/components/views/TimerDisplay.tsx
- mobile/src/navigations/HomeStack.tsx
- mobile/src/screens/EditWindowScreen.tsx
- mobile/src/screens/EventScreen.tsx
- mobile/src/screens/OnboardingScreen.tsx
- mobile/src/screens/SleepTimerScreen.tsx
- mobile/src/utils/db.tsx
- connect sleep timer to database
- Added button to indicate crib time
https://septeam4.atlassian.net/browse/T4-82
> SleepTimer backend integrate

- backend/prisma/seed.ts
- docker-compose.yml
- web/Dockerfile
- web/jest.config.cjs
- web/src/App.tsx
- web/src/__tests__/components/ClientAdminOptions.test.tsx
- web/src/__tests__/components/CoachCard.test.tsx
- web/src/__tests__/pages/AdminPage.test.tsx
- web/src/__tests__/pages/AssignPage.test.tsx
- web/src/__tests__/pages/BabyDetailsPage.test.tsx
- web/src/__tests__/pages/ClientsPage.test.tsx
- web/src/__tests__/pages/CoachPage.test.tsx
- web/src/components/ClientAdminOptions.tsx
- web/src/components/ClientCard.tsx
- web/src/components/CoachCard.tsx
- web/src/components/Sidebar.tsx
- web/src/pages/AdminPage.tsx
- web/src/pages/AssignPage.tsx
- web/src/pages/BabyDetailsPage.tsx
- web/src/pages/ClientsPage.tsx
- web/src/pages/CoachPage.tsx
- web/src/util/apiURL.tsx
- web/src/util/environment.ts
- yarn.lock
Creates a UI workflow for the owner to assign and unassign clients to coaches.  Adds AdminPage, AssignPage, CoachPage, CoachCard, and ClientAdminOptions components.  Makes a few adjacent fixes to the docker, secrets handling, and tests of other components.
https://septeam4.atlassian.net/browse/T4-36
https://septeam4.atlassian.net/browse/T4-92
The failing test below is in another component I believe someone updated the route URL but not the test URL
> Coach client control

- mobile/__tests__/screens/HomeScreen.test.tsx
- mobile/__tests__/screens/SleepPlan.test.tsx
- mobile/__tests__/utils/notifications.test.tsx
- mobile/ios/mobile.xcodeproj/project.pbxproj
- mobile/src/navigations/HomeStack.tsx
- mobile/src/screens/HomeScreen.tsx
- mobile/src/screens/SleepPlan.tsx
- mobile/src/screens/SleepTimerScreen.tsx
- mobile/src/utils/db.tsx
- mobile/src/utils/notifications.tsx
Creates notification system for Home screen based on baby's recommended plan. This right now only works for one baby. Once we implement multiple babies in the mobile app, I'll update it. 
https://septeam4.atlassian.net/browse/T4-6?atlOrigin=eyJpIjoiZDU3OTQwYmRjNjc0NGZkNGI3MTFiNDA4OGMxZDRkN2EiLCJwIjoiaiJ9
> [feat] Notification system

- mobile/__tests__/screens/OnboardingScreen.test.tsx
- mobile/__tests__/screens/SleepTimerScreen.test.tsx
- mobile/__tests__/screens/StatisticScreen.test.tsx
- mobile/package.json
- mobile/src/components/inputs/EditTimePicker.tsx
- mobile/src/screens/EditWindowScreen.tsx
- mobile/src/screens/OnboardingScreen.tsx
- mobile/src/screens/SleepTimerScreen.tsx
Added alert where needed (see pictures below)
https://septeam4.atlassian.net/browse/T4-81
> Data validation for mobile

- backend/src/controllers/answers.ts
- backend/src/routes/answers.ts
- backend/src/services/answers.ts
- backend/test/api/answers.test.ts
- backend/test/prismaSpy.ts
- mobile/__tests__/screens/EventScreen.test.tsx
- mobile/__tests__/screens/EventsScreen.test.tsx
- mobile/__tests__/screens/ProfileScreen.test.tsx
- mobile/src/screens/EventScreen.tsx
- mobile/src/screens/EventsScreen.tsx
- mobile/src/screens/OnboardingScreen.tsx
- mobile/src/screens/ProfileScreen.tsx
- mobile/src/utils/db.tsx
Adds editable event details and profile screens. 
No ticket
> [feat] Profile screen and Event Details screen

- backend/prisma/questionData.ts
- mobile/__tests__/screens/EditWindowScreen.test.tsx
- mobile/__tests__/screens/ManualSleepTrackingScreen.test.tsx
- mobile/src/navigations/HomeStack.tsx
- mobile/src/screens/ManualSleepTrackingScreen.tsx
- mobile/src/screens/SleepTimerScreen.tsx
- mobile/src/screens/TestScreen.tsx
Created a manual sleep log screen
https://septeam4.atlassian.net/browse/T4-96
https://github.com/uiowaSEP2024/004_SleepTrak/assets/21251976/fccb5130-60a9-4b1a-82c3-06b96c13bb7b
> Manual sleep track

- backend/prisma/seed.ts
Makes small changes to seed file.
N/A
> [fix] Seed changes

- backend/src/routes/events.ts
- backend/src/services/events.ts
- web/src/App.tsx
- web/src/__tests__/components/ClientCard.test.tsx
- web/src/__tests__/components/EventLogs.test.tsx
- web/src/__tests__/components/Sidebar.test.tsx
- web/src/components/ClientCard.tsx
- web/src/components/EventLogs.tsx
- web/src/components/Sidebar.tsx
- web/src/pages/DashboardPage.tsx
- web/src/pages/LogPage.tsx
Coaches can see the events logs in the logs page.
https://septeam4.atlassian.net/browse/T4-66?atlOrigin=eyJpIjoiZTE4MjkzNTcyMGE5NDFjZWJhZTY5YzVmZmQ4YzM5MmYiLCJwIjoiaiJ9
> Event Logs

- mobile/src/navigations/MainNavigator.tsx
- mobile/src/screens/EventsScreen.tsx
- mobile/src/screens/HomeScreen.tsx
- mobile/src/screens/ManualSleepTrackingScreen.tsx
- mobile/src/screens/OnboardingScreen.tsx
- mobile/src/screens/SleepTimerScreen.tsx
- mobile/src/utils/notifications.tsx
Fixes a bunch of warnings around the mobile app.
N/A
- [ x I have performed a self-review of my code
> [fix] Fixes misc warnings

- mobile/__tests__/screens/SettingScreen.test.tsx
- mobile/src/screens/SettingScreen.tsx
Created a button that navigates to the user manual in notion
https://septeam4.atlassian.net/browse/T4-97
> [feat] Link to user manual mobile 

- backend/prisma/seed.ts
Makes it so that all users have a baby
N/A
- [ x I have performed a self-review of my code
> [fix] fixes seeding of babies in db
